spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdatadb
    username: ilqar
    password : 12345
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8088


  servlet:
    context-path: /api
